### PR TITLE
v0.0.2

### LINKED ISSUE #2: Logger v1.0.0 setup
### Describe the problem

# Logger v1.0.0

## Configuration

Types and structure of possible logger configuration:

```ts
// ?: means unnecessary or can be default value
const options: {
  path?: string; // Absolute or relative path, by default no logs into files
  keep?: number; // delete after N days, 0 - disable, (default: 1 if path specified else 0)
  home?: string; // Remove that part from Error paths.
  mark?: string; // Some additional information for the logs
  logLevel?: number; // Disable logs under this log level
  timeFormat?: string; // Stdout time format (default: h:m:s)
  write?: { // Write settings
    consoleMethod?: (...args: any) => void; // console.log or process.stdout.write (default: console.log)
    interval?: [number, number] | number, // flush log to disk and console intervals (default: 300ms)
    buffer?: number, // buffer size (default: 64kb)
  };
  methods?: { // Console methods
    // ...defaultMethods
    info?: { // By default all console methods
      color: string; // R;G;B (default: 255;255;255) or some gray color
      level?: number; // Important level (default: 0), bigger = more important.
      parser?: (...args: any) => [string, string] | string; // Custom message parser, [stdout, file] | universal
      callback?: async (...args: any) => void; // Custom callback function, can be used to provide logs to other API.
    }
    // Can be new methods such as myOwnLogMethod
  };
};
```

## Usage

My vision of logger usage:

```js
const Logger = require('astrolog');

// Possible configuration
const opts = {
  path: './log',
  keep: 5,
  home: process.cwd(),
  mark: 'Worker №7',
  logLevel: 0,
  timeFormat: 'd:m:s.i', // i means millisecond
  write: {
    interval: [300, 3000],
    buffer: 64 * 1024,
    consoleMethod: process.stdout.write
  },
  methods: {
    myOwnLogMethod: [
      color: "0;0;255",
      level: 3,
      parser: (message) => message + ' custom handler',
      callback: (message) => {},
    ]
  }
}

(async () => {
  const logger = await Logger.open(opts); // Static method
  // const logger = await new Logger(opts) Or standard way

  const { console } = logger;
  console.log('Test message');
  console.error('Error message');
  // All console methods
  // For the start - log, error, clear, dir, table, warn, info, debug, assert

  await logger.close();
})();
```

### Describe the solution

_No response_

### Alternatives

_No response_

### Additional context

# More about some console methods

## Methods <code>console.error</code> and <code>console.debug</code> 

This methods should parse thrown error to make **Errors** more readable.

### For example

```javascript
const Logger = require('astrolog');
const console = Logger(/* Some options */);
console.error(new Error('Testing console.error')); 
// Error: Testing console.error /path/to/executable-file.js:row:column
```

> In configuration we have home options, its allow us to remove this part of path from Error.

## Additional

Would be great if repeated messages will be replaced by message + counter

### For example

```javascript
const Logger = require('astrolog');
const console = Logger(/* Some options */);
console.error(new Error('Testing console.error')); 
console.error(new Error('Testing console.error')); 
console.error(new Error('Testing console.error')); 
// ... old messages, before first log
// Error: Testing console.error /path/to/executable-file.js:row:column #3
```

### PR DESCRIPTION
**Pull request by Expertrix**
- [x] tests and linter show no problems (`npm t`)
- [x] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [x] description of changes is added in CHANGELOG.md
- [x] update .d.ts typings

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -2,90 +2,116 @@
...
-      setTimeout(() => {
-        const formattedMessage = formatMessage(level, message);
-        stream.write(`${formattedMessage}\n`);
-        process.stdout.write(`${formattedMessage}\n`);
-      }, delay);
-    };
-  });
+  const getColorForLevel = (level, message) => {
+    switch (level) {
+      case 'INFO':
```
Comment (sashapop10) [inline lib/index.js:77]: Use RGB syntax for compatibility

**Comment by shuritch** [comment]
After all, please de composite your logic to some code blocks at least. 

Like:

```javascript
// logger.js
const createLogger = (...
module.exports = createLogger;
```

```javascript
//files.js
const checkDir = (...
```
